import { randomUUID } from 'node:crypto';
import type { ProviderAdapter } from '@swarm/provider-core';
import type { ApprovalRequest, Repo, TaskIntent, TaskPlan, TaskRun, Workspace } from '@swarm/domain';
import { evaluatePublishPolicy } from '@swarm/policy';
import { createOrUpdateDraftPr } from '@swarm/github';

export interface RuntimeStore {
  workspaces: Workspace[];
  repos: Repo[];
  intents: TaskIntent[];
  plans: TaskPlan[];
  runs: TaskRun[];
  approvals: ApprovalRequest[];
}

export class SwarmOrchestrator {
  constructor(private readonly provider: ProviderAdapter, private readonly store: RuntimeStore) {}

  createWorkspace(name: string): Workspace {
    const workspace: Workspace = { id: randomUUID(), name, createdAt: new Date().toISOString() };
    this.store.workspaces.push(workspace);
    return workspace;
  }

  createRepo(workspaceId: string, fullName: string): Repo {
    const [owner, repoName] = fullName.split('/');
    const repo: Repo = {
      id: randomUUID(),
      workspaceId,
      name: repoName,
      fullName,
      defaultBranch: 'main'
    };
    this.store.repos.push(repo);
    return repo;
  }

  async runIntent(workspaceId: string, repoId: string, prompt: string) {
    const intent: TaskIntent = {
      id: randomUUID(), workspaceId, repoId, prompt, state: 'planned', createdAt: new Date().toISOString()
    };
    this.store.intents.push(intent);

    const planSteps = await this.provider.planTask(prompt);
    const plan: TaskPlan = {
      id: randomUUID(), intentId: intent.id, steps: planSteps, state: 'queued', createdAt: new Date().toISOString()
    };
    this.store.plans.push(plan);

    const execution = await this.provider.executeTask(plan.steps);
    const validation = await this.provider.validateTask(execution.summary);
    const review = await this.provider.reviewTask(validation);

    const run: TaskRun = {
      id: randomUUID(),
      planId: plan.id,
      state: 'awaiting_approval',
      createdAt: new Date().toISOString(),
      timeline: [
        { at: new Date().toISOString(), state: 'planned', note: 'Task intent parsed' },
        { at: new Date().toISOString(), state: 'queued', note: 'Task plan created' },
        { at: new Date().toISOString(), state: 'running', note: execution.summary },
        { at: new Date().toISOString(), state: 'validating', note: validation },
        { at: new Date().toISOString(), state: 'awaiting_approval', note: review }
      ],
      artifacts: [
        { id: randomUUID(), kind: 'plan', body: plan.steps.join('\n'), createdAt: new Date().toISOString() },
        { id: randomUUID(), kind: 'execution_log', body: execution.artifacts.join('\n'), createdAt: new Date().toISOString() },
        { id: randomUUID(), kind: 'validation_report', body: validation, createdAt: new Date().toISOString() },
        { id: randomUUID(), kind: 'review_report', body: review, createdAt: new Date().toISOString() }
      ]
    };
    this.store.runs.push(run);

    const approval: ApprovalRequest = { id: randomUUID(), runId: run.id, status: 'pending', createdAt: new Date().toISOString() };
    this.store.approvals.push(approval);

    return { intent, plan, run, approval };
  }

  async approveAndPublish(runId: string) {
    const approval = this.store.approvals.find((item) => item.runId === runId);
    if (!approval) throw new Error('Approval request not found');
    approval.status = 'approved';
    approval.resolvedAt = new Date().toISOString();

    const run = this.store.runs.find((item) => item.id === runId);
    if (!run) throw new Error('Run not found');

    const decision = evaluatePublishPolicy('draft_pr');
    if (!decision.allowed) {
      run.state = 'blocked';
      return { run, publish: null, reason: decision.reason };
    }

    run.state = 'publishing';
    const publish = await createOrUpdateDraftPr({
      owner: 'demo', repo: 'repo', branch: `swarm/${run.id.slice(0, 8)}`, title: 'Automated change', body: 'Generated by codex-github-swarm'
    });
    run.timeline.push({ at: new Date().toISOString(), state: 'publishing', note: publish.message });
    run.artifacts.push({ id: randomUUID(), kind: 'publish_result', body: JSON.stringify(publish), createdAt: new Date().toISOString() });
    run.state = 'published';

    return { run, publish, reason: null };
  }
}
